/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Subject;
import model.Teacher;

/**
 *
 * @author tharindu
 */
public class NewTeacher extends javax.swing.JFrame {

    private HashMap<String, Integer> subjectMap = new HashMap<>();
    private Vector<Integer> selectedSubjects = new Vector<>();

    /**
     * Creates new form NewTeacher
     */
    public NewTeacher() {
        initComponents();
        this.loadSubjects();
    }

    public void loadSubjects() {
        try {
            ResultSet subjects = Subject.all();
            Vector items = new Vector();
            items.add("Select a subject");
            while (subjects.next()) {
                items.add(subjects.getString("name"));
                subjectMap.put(subjects.getString("name"), subjects.getInt("id"));
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(items);
            cbSubject.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Clear() {
        tbName.setText("");
        tbAddress.setText("");
        tbMobile.setText("");

        tbName.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbMobile = new javax.swing.JTextField();
        tbAddress = new javax.swing.JTextField();
        tbName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbSubject = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 868, -1));

        tbMobile.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tbMobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(tbMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 187, 456, 40));

        tbAddress.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tbAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(tbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 284, 456, 40));

        tbName.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tbName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(tbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 103, 456, 40));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(32, 134, 234));
        jButton1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 453, 150, 50));

        jButton2.setBackground(new java.awt.Color(249, 69, 89));
        jButton2.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Teacher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 453, 350, 50));

        jButton3.setBackground(new java.awt.Color(249, 69, 89));
        jButton3.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 362, 150, 40));

        cbSubject.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        cbSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Subject", "Male", "Female" }));
        cbSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(cbSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 362, 291, 40));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Subjects");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 342, 64, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 261, 50, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mobile");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 167, 100, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subjects"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 103, 277, 299));

        jButton4.setBackground(new java.awt.Color(32, 134, 234));
        jButton4.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 453, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 869, 544));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = tbName.getText();
        String address = tbAddress.getText();
        String mobile = tbMobile.getText();

        Vector vector = new Vector();
        vector.add(name);
        vector.add(address);
        vector.add(mobile);

        boolean isValid = true;

        for (var item : vector) {
            if (String.valueOf(item).isBlank()) {
                isValid = false;
            }
        }

        if (!isValid) {
            JOptionPane.showMessageDialog(this, "Please Fill All TextFields", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Teacher isExist = new Teacher("mobile", mobile);
        if (isExist.getMobile() != null) {
            JOptionPane.showMessageDialog(this, "This Teacher Already Exist", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Teacher teacher = new Teacher();
        teacher.setName(name);
        teacher.setAddress(address);
        teacher.setMobile(mobile);

        teacher.save();

        this.Clear();

        new Teacher("mobile", mobile).addSubjects(selectedSubjects);

        JOptionPane.showMessageDialog(this, "New Teacher Added", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (cbSubject.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a subject", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = subjectMap.get(String.valueOf(cbSubject.getSelectedItem()));

        if (selectedSubjects.contains(id)) {
            JOptionPane.showMessageDialog(this, "This Subject Already Added", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedSubjects.add(id);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Vector<String> row = new Vector<>();
        row.add(String.valueOf(cbSubject.getSelectedItem()));

        model.addRow(row);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int row = jTable1.getSelectedRow();
            String subject = String.valueOf(jTable1.getValueAt(row, 0));

            int id = subjectMap.get(subject);

            Integer remove = id;
            selectedSubjects.remove(remove);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSubject;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tbAddress;
    private javax.swing.JTextField tbMobile;
    private javax.swing.JTextField tbName;
    // End of variables declaration//GEN-END:variables

}
