/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.SpecialClass;
import model.Subject;

/**
 *
 * @author User
 */
public class SpecialClz extends javax.swing.JFrame {

    private HashMap<String, Integer> subjectMap = new HashMap<>();
    private HashMap<String, Integer> teacherMap = new HashMap<>();

    /**
     * Creates new form SpacialClz
     */
    public SpecialClz() {
        initComponents();
        this.loadSubjects();
        this.loadTeachers();
    }

    public void loadSubjects() {
        try {
            ResultSet subjects = Subject.all();
            Vector items = new Vector();
            items.add("Select a subject");
            while (subjects.next()) {
                items.add(subjects.getString("name"));
                subjectMap.put(subjects.getString("name"), subjects.getInt("id"));
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(items);
            cbSubject.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadTeachers() {
        try {
            ResultSet teachers = model.Teacher.all();

            Vector items = new Vector();
            items.add("Select a Teacher");

            while (teachers.next()) {
                items.add(teachers.getString("name"));
                teacherMap.put(teachers.getString("name"), teachers.getInt("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(items);
            cbTeachers.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Clear() {
        cbSubject.setSelectedIndex(0);
        cbTeachers.setSelectedIndex(0);
        tbDate.setText("");
        tbStartTime.setText("");
        tbEndTime.setText("");

        cbSubject.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbEndTime = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tbStartTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tbDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbSubject = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbTeachers = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        dateChooser1.setForeground(new java.awt.Color(249, 69, 89));
        dateChooser1.setDateFormat("yyyy-MM-dd");
        dateChooser1.setTextRefernce(tbDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add A Special Class");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 944, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Start Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 275, -1, -1));

        tbEndTime.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tbEndTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEndTimeActionPerformed(evt);
            }
        });
        getContentPane().add(tbEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 298, 411, 40));

        jButton2.setBackground(new java.awt.Color(249, 69, 89));
        jButton2.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Class");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 391, 350, 50));

        tbStartTime.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tbStartTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(tbStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 298, 414, 40));

        jButton1.setBackground(new java.awt.Color(32, 134, 234));
        jButton1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 391, 150, 50));

        tbDate.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        tbDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(tbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 208, 843, 40));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Subject");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 90, 100, 20));

        cbSubject.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        cbSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Subject", "Sinhala", "Maths", "Science", "English", "Tamil" }));
        cbSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        cbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(cbSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 117, 414, 39));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 185, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teacher's Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 92, 107, -1));

        cbTeachers.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        cbTeachers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Teacher", "Mr.Saman Kumara", "Mrs.Swarna Perera", "Ms.Nethmi Gunawardhane" }));
        cbTeachers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        cbTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTeachersActionPerformed(evt);
            }
        });
        getContentPane().add(cbTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 116, 413, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("End Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 275, -1, -1));

        jButton3.setBackground(new java.awt.Color(32, 134, 234));
        jButton3.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 390, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 950, 505));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEndTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEndTimeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String subject = String.valueOf(cbSubject.getSelectedItem());
        String teacher = String.valueOf(cbTeachers.getSelectedItem());
        String date = tbDate.getText();
        String startTime = tbStartTime.getText();
        String endTime = tbEndTime.getText();

        Vector validate = new Vector();
        validate.add(subject);
        validate.add(teacher);
        validate.add(date);
        validate.add(startTime);
        validate.add(endTime);

        boolean isValid = true;

        for (var item : validate) {
            if (item.equals("")) {
                isValid = false;
            }
        }

        if (!isValid) {
            JOptionPane.showMessageDialog(this, "Please Fill All TextFields", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            SpecialClass classs = new SpecialClass();
            classs.setTeacher(String.valueOf(teacherMap.get(teacher)));
            classs.setSubject(String.valueOf(subjectMap.get(subject)));
            classs.setDate(date);
            classs.setStartTime(startTime);
            classs.setEndTime(endTime);

            classs.save();

            JOptionPane.showMessageDialog(this, "Special Class Scheduled", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSubjectActionPerformed

    private void cbTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTeachersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTeachersActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecialClz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecialClz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecialClz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecialClz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecialClz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSubject;
    private javax.swing.JComboBox<String> cbTeachers;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tbDate;
    private javax.swing.JTextField tbEndTime;
    private javax.swing.JTextField tbStartTime;
    // End of variables declaration//GEN-END:variables
}
