/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.Vector;
import javax.swing.JOptionPane;
import model.Student;

/**
 *
 * @author tharindu
 */
public class StudentMoreInformation extends javax.swing.JFrame {

    private Student student;

    /**
     * Creates new form StudentMoreInformation
     */
    public StudentMoreInformation(String sid) {
        initComponents();
    }

    public StudentMoreInformation() {
        initComponents();
    }

    public void Clear() {
        tbName.setText("");
        tbDOB.setText("");
        tbAddress.setText("");
        tbEmail.setText("");
        tbMobile.setText("");
        tbSID.setText("");
        cbGender.setSelectedIndex(0);

        tbSID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tbEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tbSID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tbName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbDOB = new javax.swing.JTextField();
        tbMobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbAddress = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbGender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Teacher", "Joined At"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 450, 421));

        tbEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEmailActionPerformed(evt);
            }
        });
        jPanel1.add(tbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 32));

        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        tbSID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        jPanel1.add(tbSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 185, 32));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 105, 32));

        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        tbName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        jPanel1.add(tbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 400, 32));

        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setText("Date Of Birth");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        tbDOB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDOBActionPerformed(evt);
            }
        });
        jPanel1.add(tbDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 32));

        tbMobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMobileActionPerformed(evt);
            }
        });
        jPanel1.add(tbMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 200, 32));

        jLabel6.setText("Mobile");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 60, -1));

        jLabel8.setText("Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 50, -1));

        tbAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAddressActionPerformed(evt);
            }
        });
        jPanel1.add(tbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 400, 32));

        jButton2.setBackground(new java.awt.Color(249, 69, 89));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 105, 32));

        jButton3.setBackground(new java.awt.Color(29, 107, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 70, 32));

        jButton4.setBackground(new java.awt.Color(244, 172, 24));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Update");
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 105, 32));

        jButton5.setBackground(new java.awt.Color(29, 107, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 80, 32));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        cbGender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        jPanel1.add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEmailActionPerformed

    private void tbDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDOBActionPerformed

    private void tbMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMobileActionPerformed

    private void tbAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAddressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.student = null;
        String id = tbSID.getText();
        if (id.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please Enter A Student ID", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Student student = new Student("id", id);
        if (student.getName() == null) {
            JOptionPane.showMessageDialog(this, "Invalid Student ID", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        tbName.setText(student.getName());
        tbDOB.setText(student.getDate());
        tbMobile.setText(student.getMobile());
        tbEmail.setText(student.getEmail());
        tbAddress.setText(student.getAddress());
        cbGender.setSelectedIndex(Integer.parseInt(student.getGender()));

        this.student = student;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.Clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.student == null) {
            JOptionPane.showMessageDialog(this, "Please search a student", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.student.remove();
        this.Clear();
        JOptionPane.showMessageDialog(this, "Successfully Removed", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = tbName.getText();
        String date = tbDOB.getText();
        String email = tbEmail.getText();
        String address = tbAddress.getText();
        String mobile = tbMobile.getText();
        int gender = cbGender.getSelectedIndex();

        Vector vector = new Vector();
        vector.add(name);
        vector.add(date);
        vector.add(email);
        vector.add(address);
        vector.add(mobile);

        boolean isValid = true;
        for (var item : vector) {
            if (String.valueOf(item).isBlank()) {
                isValid = false;
            }
        }

        if (gender == 0) {
            isValid = false;
        }

        if (!isValid) {
            JOptionPane.showMessageDialog(this, "Please Fill All Values", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.student.setName(name);
        this.student.setAddress(address);
        this.student.setDate(date);
        this.student.setEmail(email);
        this.student.setMobile(mobile);
        this.student.setGender(String.valueOf(gender));
        
        this.student.save();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMoreInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tbAddress;
    private javax.swing.JTextField tbDOB;
    private javax.swing.JTextField tbEmail;
    private javax.swing.JTextField tbMobile;
    private javax.swing.JTextField tbName;
    private javax.swing.JTextField tbSID;
    // End of variables declaration//GEN-END:variables
}
