/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Common;
import model.Subject;
import model.Teacher;

/**
 *
 * @author tharindu
 */
public class TeacherMoreInformation extends javax.swing.JFrame {

    private HashMap<String, Integer> subjectMap = new HashMap<>();
    private Vector<Integer> selectedSubjects = new Vector<>();

    private Teacher searchedTeacher;

    /**
     * Creates new form TeacherMoreInformation
     */
    public TeacherMoreInformation() {
        initComponents();
        this.loadSubjects();
    }

    public void loadSubjects() {
        try {
            ResultSet subjects = Subject.all();
            Vector items = new Vector();
            items.add("Select a subject");
            while (subjects.next()) {
                items.add(subjects.getString("name"));
                subjectMap.put(subjects.getString("name"), subjects.getInt("id"));
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(items);
            cbSubject.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Clear() {
        tbTID.setText("");
        tbName.setText("");
        tbMobile.setText("");
        tbAddress.setText("");
        cbSubject.setSelectedIndex(0);

        tbTID.grabFocus();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        selectedSubjects.removeAllElements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tbName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbTID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tbMobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbAddress = new javax.swing.JTextField();
        cbSubject = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 450, 421));

        tbName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNameActionPerformed(evt);
            }
        });
        getContentPane().add(tbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 120, 400, 31));

        jLabel1.setText("Teacher ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel9.setText("New Subject");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 310, 84, -1));

        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 59, -1));

        tbTID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(tbTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 185, 32));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 105, 32));

        tbMobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMobileActionPerformed(evt);
            }
        });
        getContentPane().add(tbMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 190, 400, 32));

        jLabel6.setText("Mobile");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 169, -1, -1));

        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 240, 50, -1));

        tbAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        tbAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAddressActionPerformed(evt);
            }
        });
        getContentPane().add(tbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 260, 400, 32));

        cbSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 69, 89), 1, true));
        getContentPane().add(cbSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 329, 313, 32));

        jButton2.setBackground(new java.awt.Color(249, 69, 89));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 105, 32));

        jButton3.setBackground(new java.awt.Color(29, 107, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, 32));

        jButton6.setBackground(new java.awt.Color(249, 69, 89));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add");
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 329, -1, 32));

        jButton4.setBackground(new java.awt.Color(244, 172, 24));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Update");
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 105, 32));

        jButton5.setBackground(new java.awt.Color(29, 107, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 80, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.searchedTeacher == null) {
            JOptionPane.showMessageDialog(this, "Please Search A Teacher", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.searchedTeacher.remove();
        JOptionPane.showMessageDialog(this, "Teacher Removed Successfully", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMobileActionPerformed

    private void tbAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAddressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.searchedTeacher = null;

        String id = tbTID.getText();
        this.Clear();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter A Teacher ID", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Teacher teacher = new Teacher("id", id);
        if (teacher.getAddress() == null) {
            JOptionPane.showMessageDialog(this, "Invalid Teacher ID", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.searchedTeacher = teacher;

        tbName.setText(teacher.getName());
        tbMobile.setText(teacher.getMobile());
        tbAddress.setText(teacher.getAddress());

        try {
            ResultSet subjects = teacher.getSubjects();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (subjects.next()) {
                Vector<String> row = new Vector<>();
                int subjectID = subjects.getInt("subject_id");
                String subject = String.valueOf(Common.getKeyFromValue(subjectMap, subjectID));

                row.add(subject);
                model.addRow(row);

                selectedSubjects.add(subjectID);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.Clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (this.searchedTeacher == null) {
            JOptionPane.showMessageDialog(this, "Please Search A Teacher", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String name = tbName.getText();
        String address = tbAddress.getText();
        String mobile = tbMobile.getText();

        Vector vector = new Vector();
        vector.add(name);
        vector.add(address);
        vector.add(mobile);

        boolean isValid = true;

        for (var item : vector) {
            if (String.valueOf(item).isBlank()) {
                isValid = false;
            }
        }

        if (!isValid) {
            JOptionPane.showMessageDialog(this, "Please Fill All TextFields", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Teacher teacher = searchedTeacher;
        teacher.setName(name);
        teacher.setAddress(address);
        teacher.setMobile(mobile);

        teacher.save();

        teacher.addSubjects(selectedSubjects);
        this.Clear();

        JOptionPane.showMessageDialog(this, "Teacher Updated Successfully", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (this.searchedTeacher == null) {
            JOptionPane.showMessageDialog(this, "Please Search A Teacher", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cbSubject.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a subject", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = subjectMap.get(String.valueOf(cbSubject.getSelectedItem()));

        if (selectedSubjects.contains(id)) {
            JOptionPane.showMessageDialog(this, "This Subject Already Added", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedSubjects.add(id);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Vector<String> row = new Vector<>();
        row.add(String.valueOf(cbSubject.getSelectedItem()));

        model.addRow(row);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int row = jTable1.getSelectedRow();
            String subject = String.valueOf(jTable1.getValueAt(row, 0));

            int id = subjectMap.get(subject);

            Integer remove = id;
            selectedSubjects.remove(remove);
            searchedTeacher.removeSubject(id);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherMoreInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherMoreInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSubject;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tbAddress;
    private javax.swing.JTextField tbMobile;
    private javax.swing.JTextField tbName;
    private javax.swing.JTextField tbTID;
    // End of variables declaration//GEN-END:variables
}
